name: ligo
channels:
  - conda-forge
dependencies:
  - python=2.7 #.15
  - numpy=1.16 #.6
  - scipy=1.2 #.3
  - h5py=2.10 #.0
  - matplotlib=2.2 #.5
  - IPython=5.8 #.0
  - ipykernel=4.8 #.2
  - decorator=4.4 #.2